apps/accounts/api/urls.py
from django.urls import path
from rest_framework_jwt import views

app_name = "users"

urlpatterns = [
    path("login/", views.obtain_jwt_token, name="jwt_login"),
    path("token/refresh/", views.refresh_jwt_token, name="refresh_jwt_token"),
]

apps/accounts/urls.py
from django.urls import path

import apps.accounts.views as views

urlpatterns = [
    path("sign-in/", views.CustomUserLoginView.as_view(), name="sign_in"),
    path(
        "sign-in/success/",
        views.CustomUserLoginSuccessView.as_view(),
        name="sign_in_success",
    ),
    path("profile/<int:pk>", views.CustomUserProfile.as_view(), name="profile"),
    path("logout/", views.CustomUserLogoutView.as_view(), name="logout"),
    path("sign-up/", views.CustomUserSignUpView.as_view(), name="sign_up"),
    path(
        "password_reset/",
        views.CustomUserResetPasswordView.as_view(),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        views.CustomUserPasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.CustomUserResetPasswordConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.CustomUserPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

yalantis-django/urls.py
import debug_toolbar
from . import views

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include(debug_toolbar.urls)),
    path("", views.home, name="base"),
    path("about-us", views.about_us, name="about_us"),
    path("authors", views.authors, name="authors"),
    path("contacts", views.contacts, name="contacts"),
    path(
        "accounts/", include(("apps.accounts.urls", "accounts"), namespace="accounts")
    ),
    path("api/v1/auth/", include("apps.accounts.api.urls", namespace="api_auth")),
    path("api/v1/", include("apps.dialogs.api.urls", namespace="api_dialogs")),
]

apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse_lazy

from .managers import UserManager


class User(AbstractUser):
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=50)
    password_expire_at = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = UserManager()

    class Meta:
        ordering = ("-created_at",)
        verbose_name = "User"
        verbose_name_plural = "Users"

    def get_absolute_url(self):
        return reverse_lazy("accounts:profile", kwargs={"pk": self.pk})

    def __str__(self):
        return self.email

apps/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.db.models import Q
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode

User = get_user_model()


class CustomPasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        del self.fields["email"]

    username_email = forms.CharField(max_length=254)

    class Meta:
        model = User
        fields = ("username_email",)

    def clean_username_email(self):
        username_email = self.cleaned_data.get("username_email")
        try:
            User.objects.get(
                Q(username__iexact=username_email) | Q(email__iexact=username_email)
            )
        except User.DoesNotExist:
            raise ValidationError(
                "The username/email you entered is not registered. "
                "Please enter valid username/email."
            )
        return username_email

    def get_users(self, username_email):
        """Given an email, return matching user(s) who should receive a reset.

        This allows subclasses to more easily customize the default policies
        that prevent inactive users and users with unusable passwords from
        resetting their password.
        """
        active_users = User._default_manager.filter(
            Q(username__iexact=username_email) | Q(email__iexact=username_email),
            is_active=True,
        )
        return (u for u in active_users if u.has_usable_password())

    def save(
            self,
            domain_override=None,
            subject_template_name="registration/password_reset_subject.txt",
            email_template_name="registration/password_reset_email.html",
            use_https=False,
            token_generator=default_token_generator,
            from_email=None,
            request=None,
            html_email_template_name=None,
            extra_email_context=None,
    ):
        """
        Generates a one-use only link for resetting password and sends to the
        user.
        """
        username_email = self.cleaned_data["username_email"]
        for user in self.get_users(username_email):
            if not domain_override:
                current_site = get_current_site(request)
                site_name = current_site.name
                domain = current_site.domain
            else:
                site_name = domain = domain_override
            context = {
                "email": user.email,
                "domain": domain,
                "site_name": site_name,
                "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                "user": user,
                "token": token_generator.make_token(user),
                "protocol": "https" if use_https else "http",
            }

            self.send_mail(
                subject_template_name,
                email_template_name,
                context,
                from_email,
                user.email,
                html_email_template_name=html_email_template_name,
            )


class CustomUserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "email",
            "username",
            "password1",
            "password2",
        ]

apps/accounts/views.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetCompleteView,
)
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import DetailView, TemplateView
from django.views.generic.edit import CreateView

from apps.accounts.forms import CustomPasswordResetForm, CustomUserRegisterForm
from apps.accounts.models import User


class CustomUserLoginView(LoginView):
    template_name = "login/login.html"


class CustomUserLoginSuccessView(TemplateView):
    template_name = "login/login_success.html"


class CustomUserLogoutView(LogoutView):
    template_name = "login/logout.html"


class CustomUserResetPasswordView(PasswordResetView):
    template_name = "reset_pass/password_reset.html"
    email_template_name = "reset_pass/password_reset_email.html"
    form_class = CustomPasswordResetForm
    success_url = reverse_lazy("accounts:password_reset_done")


class CustomUserPasswordResetDoneView(PasswordResetDoneView):
    template_name = "reset_pass/password_reset_done.html"


class CustomUserResetPasswordConfirmView(PasswordResetConfirmView):
    template_name = "reset_pass/password_reset_confirm.html"
    success_url = reverse_lazy("accounts:password_reset_complete")


class CustomUserPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = "reset_pass/password_reset_complete.html"


class CustomUserProfile(DetailView):
    model = User
    template_name = "login/profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = get_object_or_404(self.model, pk=self.kwargs.get("pk"))
        context["user"] = user
        return context


class CustomUserSignUpView(SuccessMessageMixin, CreateView):
    template_name = "signup.html"
    success_url = reverse_lazy("accounts:sign_in")
    form_class = CustomUserRegisterForm
    success_message = "Your profile was created successfully"

apps/accounts/templates/login/login.html
{% extends 'base.html' %}

{% block title %}
    Sign in
{% endblock %}

{% block content %}

    {% load crispy_forms_tags %}

    <div class="container">
        <div class="row text-center">
            <div class="col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-body">
                        <div class="login-title">
                            <h4>Login</h4>
                            <p>Use Username or Email</p>
                        </div>
                        <div class="login-form mt-4">
                            <form action="." method="post">
                                {% csrf_token %}
                                {{ form|crispy }}
                                <div class="form-row">
                                    <button type="submit" class="btn btn-danger btn-block mt-2">Submit</button>
                                </div>
                            </form>
                        </div>
                        <div class="logi-forgot text-right mt-2">
                            Forgot your password?
                            <a href="{% url 'accounts:password_reset' %}"> Reset Password </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

apps/accounts/templates/login/login_success.html
{% extends 'base.html' %}

{% block title %}
    Successfully Login
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row text-center">
            <div class="col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-body">
                        <div class="login-title">
                            <h4>Successfully Login</h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

apps/accounts/templates/login/logout.html
{% extends 'base.html' %}

{% block title %}
    Successfully Logout
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row text-center">
            <div class="col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-body">
                        <div class="login-title">
                            <h4>Successfully Logout</h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

apps/accounts/templates/login/profile.html
{% extends 'base.html' %}

{% block title %}
    Profile Details
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row text-center">
            <div class="col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-body">
                        <div class="login-title">
                            <h4>Profile Details</h4>
                            <p>Full Name: {{ user.get_full_name }}</p>
                            <p>Username: {{ user.username }}</p>
                            <p>Email: {{ user.email }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}