apps/accounts/urls.py
from django.urls import path

import apps.accounts.views as views

urlpatterns = [
    path("sign-in/", views.CustomUserLoginView.as_view(), name="sign_in"),
    path(
        "sign-in/success/",
        views.CustomUserLoginSuccessView.as_view(),
        name="sign_in_success",
    ),
    path("profile/<int:pk>", views.CustomUserProfile.as_view(), name="profile"),
    path("logout/", views.CustomUserLogoutView.as_view(), name="logout"),
    path("sign-up/", views.CustomUserSignUpView.as_view(), name="sign_up"),
    path(
        "password_reset/",
        views.CustomUserResetPasswordView.as_view(),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        views.CustomUserPasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.CustomUserResetPasswordConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.CustomUserPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

yalantis-django/urls.py
import debug_toolbar
from . import views

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include(debug_toolbar.urls)),
    path("", views.home, name="base"),
    path("about-us", views.about_us, name="about_us"),
    path("authors", views.authors, name="authors"),
    path("contacts", views.contacts, name="contacts"),
    path(
        "accounts/", include(("apps.accounts.urls", "accounts"), namespace="accounts")
    ),
    path("api/v1/auth/", include("apps.accounts.api.urls", namespace="api_auth")),
    path("api/v1/", include("apps.dialogs.api.urls", namespace="api_dialogs")),
]

templates/base.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<!------ Include the above in your HEAD tag ---------->


<html lang="en">
<head>
    <title>{% block title %} Messager {% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,500,500i,700,800i" rel="stylesheet">
</head>
<body>

<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-transparent">
    <div class="container-fluid container-xl">
        <a class="navbar-brand" href="{% url 'base' %}">
            <h1>Logo</h1>
        </a>
        <div class="navbar-toggle" data-toggle="collapse" data-target="navbarToggle" aria-controls="navbarToggle"
             aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggle-icon"></span>

        </div>

        <div class=" navbar-collapse" id="navbarToggle">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item ">
                    <a class="nav-link active" href="{% url 'base' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'about_us' %}">About us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contacts' %}">Contacts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'authors' %}">Authors</a>
                </li>
            </ul>
            <div class="nav-buttons">
                <div class="nav-item">
                    {% if request.user.is_authenticated %}
                        <a class="btn btn-round btn-outline-success btn-light ml-3 btn-sm"
                           href="{{ request.user.get_absolute_url }}">
                            Profile
                        </a>
                        <a class="btn btn-round btn-outline-primary btn-light ml-3 btn-sm"
                           href="{% url 'accounts:logout' %}">
                            Logout
                        </a>
                    {% else %}
                        <a class="btn btn-round btn-outline-primary btn-light ml-3 btn-sm"
                           href="{% url 'accounts:sign_in' %}">
                            Login
                        </a>
                    {% endif %}
                    <a class="btn btn-round btn-primary ml-3 btn-sm"
                       href="{% url 'accounts:sign_up' %}">
                        Sign Up
                    </a>
                </div>
            </div>
        </div>
    </div>
</nav>
<!-- End Navbar -->

<!-- Content -->
{% block content %} {% endblock %}
<!-- End Content -->

</body>
</html>

templates/index.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<!------ Include the above in your HEAD tag ---------->


<html lang="en">
<head>
    <title>{% block title %} Messager {% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,500,500i,700,800i" rel="stylesheet">
</head>
<body>

<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-transparent">
    <div class="container-fluid container-xl">
        <a class="navbar-brand" href="{% url 'index' %}">
            <h1>Logo</h1>
        </a>
        <div class="navbar-toggle" data-toggle="collapse" data-target="navbarToggle" aria-controls="navbarToggle"
             aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggle-icon"></span>

        </div>

        <div class=" navbar-collapse" id="navbarToggle">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item ">
                    <a class="nav-link active" href="{% url 'index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'about_us' %}">About us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contacts' %}">Contacts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'authors' %}">Authors</a>
                </li>
            </ul>
            <div class="nav-buttons">
                <div class="nav-item">
                    <a class="btn btn-round btn-outline-primary btn-light ml-3 btn-sm"
                       href="{% url 'accounts:sign_in' %}">
                        Login
                    </a>
                    <a class="btn btn-round btn-primary ml-3 btn-sm"
                       href="{% url 'accounts:sign_up' %}">
                        Sign Up
                    </a>
                </div>
            </div>
        </div>
    </div>
</nav>
<!-- End Navbar -->

<!-- Content -->
{% block content %} {% endblock %}
<!-- End Content -->

</body>
</html>